//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-IDserv-SSD_SERVICE_ID_sd_0FrKeUOH7UXlT8BD
import { IDserv as SSD_SERVICE_ID_sd_0FrKeUOH7UXlT8BD } from './sd-services/IDserv';

export const UserRoutes = [
    //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-IDserv-SSD_SERVICE_ID_sd_0FrKeUOH7UXlT8BD
SSD_SERVICE_ID_sd_0FrKeUOH7UXlT8BD,
];
