//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-idGenerator-SSD_SERVICE_ID_sd_0FrKeUOH7UXlT8BD
import { idGenerator as SSD_SERVICE_ID_sd_0FrKeUOH7UXlT8BD } from './sd-services/idGenerator';
//CORE_REFERENCE_IMPORT-Analytics-SSD_SERVICE_ID_sd_YcjR49og4q4pSsJ9
import { Analytics as SSD_SERVICE_ID_sd_YcjR49og4q4pSsJ9 } from './sd-services/Analytics';

export const UserRoutes = [
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-idGenerator-SSD_SERVICE_ID_sd_0FrKeUOH7UXlT8BD
SSD_SERVICE_ID_sd_0FrKeUOH7UXlT8BD,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-Analytics-SSD_SERVICE_ID_sd_YcjR49og4q4pSsJ9
SSD_SERVICE_ID_sd_YcjR49og4q4pSsJ9,
];
